# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TESTEAPPCENTER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TESTEAPPCENTER

  target 'TESTEAPPCENTERTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AppCenter'
end
